### ISSUE TITLE
Styles leaking into whole app

### ISSUE THREAD

**Issue by pleku** [pleku/wysiwyg-e-java#12]
>When i added wysiwyg component in a VerticalLayout and than opened it on browser wysiwyg effect whole project font style, size and weight. I am using 1.0.0.beta1 for 14.0.12 compability mode. Can yo sow me a way to fix this issue?

Based on feedback in https://vaadin.com/directory/component/wysiwyg-e-rich-text-editor-component-for-java/discussions

**Comment by pleku** [comment]
I could not replicate this with 1.0.0.rc1 running Vaadin 14.0.13 in compatibility mode, so maybe it was fixed already.

Closing the issue, please comment here and provide details like code to be able replicate it.

**Comment by emrephi** [comment]
Hi, i am using 14.0.13 and 1.0.0.rc1 and i am faceing the issue still.

1. when i using vaadin TextArea component:

![Capture1](https://user-images.githubusercontent.com/43035206/69238313-bb1ef180-0ba8-11ea-97cc-60f824e0b70b.PNG)


2. When i using WysiwygE component:

![Capture2](https://user-images.githubusercontent.com/43035206/69238318-c07c3c00-0ba8-11ea-8660-36d04468fdf9.PNG)

Result: As you see; labels and texts on the screen getting bolder and bigger, and also it changes font family....
